server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_class
    hikari:
      username: root
      password: root1234%
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # 让 hibernate不去操作表结构
      ddl-auto: none
    # 打印执行的 sql 语句，方便排查问题
    show-sql: true

  application:
    name: ms-class

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.hostname}
        tags: JIFANG=NJ

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# ./consul agent -dev -ui -client 0.0.0.0
#ms-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    server-list-refresh-interval=30000 # 缩短服务刷新时间间隔
ribbon:
  eager-load:
    # 允许饥饿加载
    enabled: true
    # 细粒度指定某些微服务使用饥饿加载，多个用逗号隔开
    clients: ms-user
logging:
  level:
    com.leekwok.msclass.feign.MsUserFeignClient: debug

# 细粒度配置
feign:
  client:
    config:
      default:
        loggerLevel: full
  httpclient:
    # 让 feign 使用 apache 的 httpclient，而不是默认的 Client.Default
    enabled: true
    # feign 的最大连接数
    max-connections: 200
    # feign 单个路径的最大连接数
    max-connections-per-route: 50

resilience4j:
  ratelimiter:
    configs:
      # 默认配置，自定义属性没有配置则用系统中预定义的配置，而不是用这里的 default 配置，如 timeoutDuration
      default:
        # 刷新周期内请求的最大频次
        limitForPeriod: 1
        # 刷新周期，也即 1s 内最大只允许 1 次请求通过
        limitRefreshPeriod: 1s
        # 线程等待许可的时间，也即第二个线程不等待，直接抛异常
        timeoutDuration: 0
      share:
        limitForPeriod: 2
    instances:
      buyById:
        # 刷新周期内请求的最大频次，引用 share 的配置项
        baseConfig: share
        # 刷新周期，也即 1s 内最大只允许 1 次请求通过
        limitRefreshPeriod: 1s

  # 舱壁模式
  bulkhead:
    instances:
      buyById:
        # 最大并发请求数
        maxConcurrentCalls: 1
        # 舱壁饱和时的最大等待时间，默认 0ms
        maxWaitDuration: 10ms
        # 事件缓冲区大小
        eventConsumerBufferSize: 1