server:
  port: 8010
spring:
  rabbitmq:
    host: 192.168.28.128
    port: 5672
  datasource:
    url: jdbc:mysql://192.168.28.128:3306/ms_class
    hikari:
      username: root
      password: root1234%
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # 让 hibernate不去操作表结构
      ddl-auto: none
    # 打印执行的 sql 语句，方便排查问题
    show-sql: true

  application:
    name: ms-class

  cloud:
    stream:
      bindings:
        output:
          destination: stream-test
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${server.port}-${spring.cloud.client.hostname}
        tags: JIFANG=NJ

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# ./consul agent -dev -ui -client 0.0.0.0
#ms-user:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    server-list-refresh-interval=30000 # 缩短服务刷新时间间隔
ribbon:
  eager-load:
    # 允许饥饿加载
    enabled: true
    # 细粒度指定某些微服务使用饥饿加载，多个用逗号隔开
    clients: ms-user
logging:
  level:
    com.leekwok.msclass.feign.MsUserFeignClient: debug

# 细粒度配置
feign:
  client:
    config:
      default:
        loggerLevel: full
  httpclient:
    # 让 feign 使用 apache 的 httpclient，而不是默认的 Client.Default
    enabled: true
    # feign 的最大连接数
    max-connections: 200
    # feign 单个路径的最大连接数
    max-connections-per-route: 50
